inherit_from: .rubocop_todo.yml
AllCops:
  DisplayCopNames: true
  Exclude:
    - message_train.gemspec
    - db/migrate/*
    - spec/dummy/db/schema.rb
    - spec/dummy/db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/*
    - spec/*/*
    - spec/*/*/*
    - spec/dummy/db/seeds/*
